### ISSUE TITLE
Can I join in?

### ISSUE THREAD

**Issue by swails** [choderalab/openmm-tests#1]
Hi John,

I was about to start up my own OpenMM test suite, but I thought it might be better in the long run to coordinate efforts so more tests get run by more people.

What do you think?  I'm in the process of figuring this repo out (there are a lot of prereqs that I didn't have).

I don't really have the time to figure out how to work my tests into your class infrastructure, so I imagine that if I join this repo, different tests will be implemented differently but I'm hopeful that we could provide a common interface to actually _run_ the tests (and to determine if they 'passed' or not).

**Comment by kyleabeauchamp** [comment]
+1 imho a realistic plan is to first add lots of tests and refactor
later.   Look around at our repex repo, which also has lots of
testsystems.  We might need to do another large refactoring / consolidation
if we eventually have a master testing repo
